import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

import { PageContainer } from "@/components/PageContainer";
import { Header } from "@/components/Header";
import { Spacer } from "@/components/UI/Spacer";
import { JanstayHello } from "@/components/JanstayHello";
import { MainText } from "@/components/MainText";
import { PortfolioCards } from "@/components/PortfolioCards";
import { Footer } from "@/components/Footer";
import { FloatingSocialLink } from "@/components/FloatingSocialLink";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        <Header />
        <Spacer heightDesktop="86px" />
        <JanstayHello />
        <Spacer heightDesktop="20px" />
        <MainText />
        <Spacer heightDesktop="60px" />
        <PortfolioCards />
        <Spacer heightDesktop="240px" heightMobile="160px" />
        <Footer />
        <FloatingSocialLink bottom="26px" />
      </PageContainer>
    </>
  );
}
